### ISSUE TITLE
Parsing information for qere

### ISSUE THREAD

**Issue by rubiot** [ETCBC/bhsa#7]
I assume there's no parsing information for qere variants, is that right? Like part of speech, number, gender, etc.

**Comment by jcuenod** [comment]
Just fyi, if you don't _need_ to stick to the ETCBC corpus, I'm pretty sure that [morphhb](https://github.com/openscriptures/morphhb/) has parsed ketiv and qere variants and that STEPBible exposes this data. You'd probably be able to find it here: https://github.com/tyndale/STEPBible-Data

**Comment by codykingham** [comment]
Thanks @jcuenod ! good tip

**Comment by oliverglanz** [comment]
@rubiot , as you probably found out already, the ETCBC data parses only the Q reading not the K writing. If you need K parsing @jcuenod's tip is great.

**Comment by rubiot** [comment]
Thank you @jcuenod and @oliverglanz for the help. I appreciate.
